### ISSUE TITLE
iframe not available

### ISSUE THREAD

**Issue by timarney** [sanderheilbron/vimeo.ga.js#12]
When loading content via ajax the script doesn't work - 'iframe is not available'.  It would be good if the code could be initialized via function call vs the IIFE

**Comment by williamvicary** [comment]
What I did to work around this is to force the request of "onReady()" at the load time of the script, move the iframe initialize code to a separate function and that every time vimeo passes "ready" that the script executes the iframe initialize code - this seems to have worked. It decreases the efficiency slightly as it is calling code more than once (such as addListener) however the functionality still works as intended and Ajax loaded scripts fire the appropriate events.
