### ISSUE TITLE
Can't seem to make it work!

### ISSUE THREAD

**Issue by trtlever** [sanderheilbron/vimeo.ga.js#26]
Hello, trying to get your amazing script to work on my page but have failed unfortunately. Would you please be able to take a look and let me know where I am going wrong?

http://beta.to-jo.co.uk

Thank you in advance!

Cheers,

Tom

**Comment by kakbeya** [comment]
@trtlever 

You have problems with your markup here:

`<script type="text/javascript">
			 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>`

Try removing `<script type="text/javascript">`

**Comment by sanderheilbron** [comment]
@trtlever Check the screenshot below:

![home](https://cloud.githubusercontent.com/assets/41921/6776467/27b98804-d13f-11e4-8013-4cdeeb835e57.png)

**Comment by trtlever** [comment]
Thanks for that @kakbeya  and @sanderheilbron. I've corrected the script tag. 

It seems to sit at an error on the vimeo script? I've included some screen shots. 

Also, excuse my idiocy but i'm only just getting going in coding - do I need to add variable to analytics to make it work or will it pull them through automatically?

![screen shot 2015-03-23 at 09 55 04](https://cloud.githubusercontent.com/assets/11604654/6778058/59e2d7ce-d147-11e4-9171-d2d251360f3b.png)
![screen shot 2015-03-23 at 09 55 26](https://cloud.githubusercontent.com/assets/11604654/6778059/5a0495c6-d147-11e4-9cc6-9df910432d0f.png)

**Comment by kakbeya** [comment]
@trtlever 

It should do it automatically.

**Comment by trtlever** [comment]
The script is still not working and is coming back with an error on the script? Is this due to a conflict?

[Error] TypeError: undefined is not a function (evaluating '$(function(){vimeoGAJS.init()})')
	global code (vimeo.ga.min.js, line 8)
