### ISSUE TITLE
GA version identification issue

### ISSUE THREAD

**Issue by ecalden** [sanderheilbron/vimeo.ga.js#27]
We're trying to implement this script to track a video on our site, but are having some issues. We are using Universal Analytics, implemented through Yoast's Analytics plugin for Wordpress. However, when we run a check on the script on our video page, we're seeing asynchronous GA calls (see screenshot). Additionally, it is pulling in a UA other than ours (UA-76641-35, which looks like it's within the main vimeo.ga.js code). We're also seeing the error "Uncaught TypeError: undefined is not a function". Any guidance on these issues is much appreciated! 

Thanks!

![image](https://cloud.githubusercontent.com/assets/11887961/7089351/3551eb18-df69-11e4-8a50-2f11fb0f470c.png)

**Comment by sanderheilbron** [comment]
The UA you are seeing is the GA tracker used by Vimeo to track all their hosted and embedded videos. 

Unfortunately I do not have any experience with Yoast's Analytics plugin for Wordpress.

**Comment by chercka** [comment]
Yoast calls the analytics object '__gaTracker' instead of 'ga' which this script expects. See how to fix this here:
