### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by jsrobinson** [sanderheilbron/vimeo.ga.js#28]
with v0.5.1

http://www.aptare.com/demo_isilon_analytics -> press play and see error in console

I'm using jQ 1.7.2

**Comment by sanderheilbron** [comment]
The iframe does not match the instructions for usage:

**Current iframe**
```html
<iframe src="//player.vimeo.com/video/99535901?api=1&title=0&amp;byline=0&amp;portrait=0" width="500" height="309" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe>
```

**Modified iframe**
```html
<iframe src="//player.vimeo.com/video/99535901?api=1&title=0&amp;byline=0&amp;portrait=0&player_id=vimeo-player-1" id="vimeo-player-1" width="500" height="309" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
```

**Comment by jsrobinson** [comment]
Thank you for the support. I didn't realize the ID and that part of the querystring were required. How can I manipulate the event name sent? How would I go about passing the name of the video being played? I didn't see the ID being used in what was sent to GA, so I am wondering how else to go about it. Ultimately, I would love to add an attribute like rel or title to the iframe tag and then have that passed to GA with the event.

**Comment by sanderheilbron** [comment]
The current version does not offer the possibility to manipulate the event names, but you could change the names inside the script itself before you include it in the page.

The ID of the video is available in the Vimeo URL. This URL is sent to Google Analytics, see this example of the output of the script:
``` javascript
ga('send', 'event', 'Vimeo', 'Started video', 'http://player.vimeo.com/video/22439234', undefined, {'nonInteraction': 1});
ga('send', 'event', 'Vimeo', 'Paused video', 'http://player.vimeo.com/video/22439234', undefined, {'nonInteraction': 1});
ga('send', 'event', 'Vimeo', 'Resumed video', 'http://player.vimeo.com/video/22439234', undefined, {'nonInteraction': 1});
ga('send', 'event', 'Vimeo', 'Completed video', 'http://player.vimeo.com/video/22439234', undefined, {'nonInteraction': 1});
ga('send', 'event', 'Vimeo', 'Skipped video forward or backward', 'http://player.vimeo.com/video/22439234', undefined, {'nonInteraction': 1});
```
