### ISSUE TITLE
Analytics No Longer Showing Data

### ISSUE THREAD

**Issue by dougfelton** [sanderheilbron/vimeo.ga.js#32]
Beginning June 13, 2015 Analytics is no longer reporting any video event data.  Since discovering this, I've updated to the latest vimeo.ga.js version, updated the HTML with the latest description in the docs, confirmed that the videos still work and play and pause etc, confirmed that Analytics is reporting pageviews traffic for the page containing the videos, and confirmed that the Vimeo account is active and that video views are being reported in the Vimeo stats.  I can find no reason for the events no longer being reported in Analytics.  Has anyone else experienced this?  Any thoughts on debugging this?

**Comment by sanderheilbron** [comment]
Which protocol (http or https) is used by the Vimeo URLs?

**Comment by dougfelton** [comment]
http

**Comment by sanderheilbron** [comment]
Could you change these to https and check if events are tracked?

**Comment by dougfelton** [comment]
Will do.  I'll update you later today or tomorrow.  Thank you.

**Comment by dougfelton** [comment]
After that change the events are now being tracked again.  Thanks so much for the quick response, helpful response, and for a really nice script.

**Comment by sanderheilbron** [comment]
Glad to see that change has helped.

Vimeo has added the HSTS response header to their video URLs recently. The HTTP Strict Transport Security feature lets a web site inform the browser that it should never load the site, or in this case the video, using HTTP, and should automatically convert all attempts to access the site or video using HTTP to HTTPS requests instead. 

Unfortunately this requirement breaks the tracking functionality inside the script. Within a few days I will update both the script and documentation.
